language: python 
python:
  - "2.7"
  - "3.5"
  - "3.6"  # current default Python on Travis CI

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
before_install:
  - pip install codecov
  - pip install coverage
script: 
  - pip install -e .[tests] --progress-bar off
  - pip install codacy-coverage
  - pytest tests --cov=pyensemble --cov-report xml:coverage.xml
  - if ! [[ -z $CODACY_PROJECT_TOKEN ]]; then
      python-codacy-coverage -r coverage.xml;
    fi
  - pip install python-coveralls && coveralls
  - pip install pytest-cover
after_success:
  - codecov
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

env:
  global:
    - CODACY_PROJECT_TOKEN=c3b63ca4c921490eb82dfd6f7afa2b98
